
  kind: pipeline
  name: nodeEval

  steps:
  - name: nodeTest
    image: node
    commands:
      - npm install -g mongodb
      - npm install
      - npm install -g mocha
      - npm -g install chai
      - npm -g install chai-http
      - npm -g install mochawesome
      - git clone  https://github.com/unsortedArray/blog-app-test-cases.git
      - cd blog-app-test-cases
      - mocha test-cases.js --reporter mochawesome --timeout 10000 --exit

services:
- name: mongo
  image: mongo:4
  command: [ --smallfiles ]
  ports:
    - 27017